services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=EduMingleDB
      - POSTGRES_PASSWORD=Siya@100
      - POSTGRES_USER=Siyabonga
    ports:
      - "5000:5432"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/EduMingleDB
      - SPRING_DATASOURCE_USERNAME=Siyabonga
      - SPRING_DATASOURCE_PASSWORD=Siya@100
  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:4200"
    links:
      - backend
  


